version : '3.8'

services :
  web:
    build: .
    prots:
      - "5000:5000"
    networks:
      - app-net
    depends_on:
      - redis

    redis:
      images: redis:apline
      volumes:
      - redis-data:/data
      networks:
        - app-net
    
    volumes:
     redis-data

    networks:
      app-net:
      